### ISSUE TITLE
Any Chance to use this in Swift?

### ISSUE THREAD

**Issue by zhigang1992** [matthewcheok/POP-MCAnimate#14]
Tried importing with CocoaPods, it keeps complaining about file not file~

Help :(

**Comment by matthewcheok** [comment]
I don't see why it wouldn't work... Do you have a sample project I could look at?

**Comment by zhigang1992** [comment]
It's was built into `POP_MCAnimate` instead of `POP-MCAnimate`. lol

**Comment by mauker** [comment]
Sorry about my stupid question, but how can I do the POP MCAnimate build on a swift project, for me I ever se the error 'POP+MCAnimate.h' file not found,
